
import { SelectableItem, Translations, KnowledgeLevel, StudyType } from './types';

export const UI_TEXT: Translations = {
  title: { en: "Sacred Studies", zh: "神聖研究" },
  subtitle: { en: "AI-Enhanced Biblical Scholarship", zh: "人工智慧輔助聖經學術研究" },
  configure: { en: "Configure", zh: "設定" },
  approaches: { en: "Approaches", zh: "詮釋方法" },
  traditions: { en: "Traditions", zh: "歷史傳統" },
  generate: { en: "Generate", zh: "生成報告" },
  back: { en: "Back", zh: "上一步" },
  next: { en: "Next Step", zh: "下一步" },
  generating: { en: "Generating...", zh: "正在生成..." },
  passageLabel: { en: "Biblical Passage", zh: "聖經經文" },
  passagePlaceholder: { en: "e.g., John 3:16-21, Psalm 23", zh: "例如：約翰福音 3:16-21, 詩篇 23" },
  topicLabel: { en: "Theological Topic (Optional)", zh: "神學主題 (選填)" },
  topicPlaceholder: { en: "Enter topic or click Auto-Generate", zh: "輸入主題或點擊自動生成" },
  autoGenerate: { en: "Auto-Generate Insightful Topic", zh: "自動生成深刻主題" },
  knowledgeLabel: { en: "Knowledge Level", zh: "知識水平" },
  typeLabel: { en: "Study Type", zh: "研究類型" },
  durationLabel: { en: "Target Duration", zh: "目標長度" },
  reviewConfig: { en: "Review Configuration", zh: "確認設定" },
  readyPrompt: { en: "Ready to Generate Study Guide", zh: "準備生成研究指南" },
  download: { en: "Export Document", zh: "匯出文件" },
  minutes: { en: "minutes", zh: "分鐘" },
  selectApproachesTitle: { en: "Interpretive Approaches", zh: "詮釋方法" },
  selectApproachesSub: { en: "Select the lenses through which you wish to analyze the text.", zh: "選擇您希望用來分析經文的視角。" },
  selectTraditionsTitle: { en: "Historical Traditions", zh: "歷史傳統" },
  selectTraditionsSub: { en: "Choose the voices from history to include in the conversation.", zh: "選擇要納入對話的歷史聲音。" },
  customApproachLabel: { en: "Custom Approach Definition", zh: "自訂詮釋方法定義" },
  customApproachPlaceholder: { en: "Describe your specific interpretive lens or combination of methods here...", zh: "在此描述您特定的詮釋視角或方法組合..." },
  autoResearchLabel: { en: "Auto-Pilot Mode (Smart Research)", zh: "自動導航模式 (智慧研究)" },
  autoResearchDesc: { en: "Skip manual selection. AI automatically determines the best methodology and conducts deep literature research.", zh: "跳過手動選擇。AI 自動決定最佳方法論並進行深度文獻研究。" },
  includeBackgroundLabel: { en: "Include Historical Context", zh: "包含歷史背景" },
  includeBackgroundDesc: { en: "Adds a dedicated section for book introduction, authorship, and historical setting.", zh: "增加一個專門的章節來介紹書卷簡介、作者歸屬和歷史背景。" },
  stepConfigure: { en: "Configure", zh: "設定" },
  stepApproaches: { en: "Approaches", zh: "詮釋方法" },
  stepTraditions: { en: "Traditions", zh: "歷史傳統" },
  stepGenerate: { en: "Generate", zh: "生成" },
  generateIdeas: { en: "Generate Ideas", zh: "獲取靈感" },
  selectTheme: { en: "Select a theme:", zh: "選擇一個主題：" },
  latestResearch: { en: "Librarian Agent Active", zh: "圖書管理員代理已啟用" },
  autoSelected: { en: "Auto-Selected by AI", zh: "由 AI 自動選擇" },
  sources: { en: "Research Grounding Sources", zh: "學術研究參考來源" },
  dashboard: { en: "Dashboard", zh: "控制面板" },
  generatePaper: { en: "Generate Paper", zh: "生成報告" },
  myLibrary: { en: "My Library", zh: "我的圖書館" },
  settings: { en: "Settings", zh: "設定" },
  newAnalysis: { en: "New Analysis", zh: "新分析" },
  nextApproaches: { en: "Next: Approaches", zh: "下一步：詮釋方法" },
  nextTraditions: { en: "Next: Traditions", zh: "下一步：歷史傳統" },
  nextReview: { en: "Next: Review", zh: "下一步：確認設定" },
  synthesizing: { en: "Synthesizing...", zh: "正在合成..." },
  saveToLibrary: { en: "Save to Library", zh: "儲存到圖書館" },
  saved: { en: "Saved Successfully", zh: "儲存成功" },
  emptyLibrary: { en: "Your library is currently empty.", zh: "您的圖書館目前是空的。" },
  delete: { en: "Delete", zh: "刪除" },
  open: { en: "Open", zh: "開啟" },
  backToLibrary: { en: "Back to Library", zh: "返回圖書館" },
  
  // Lectionary Options
  lectionaryRCL: { en: "Western (RCL)", zh: "三代經課 (RCL)" },
  lectionaryTorah: { en: "Torah Portion", zh: "猶太五經 (Parashat)" },
  lectionaryOrthodox: { en: "Eastern Orthodox", zh: "東方教會 (Orthodox)" },
  fetchingLectionary: { en: "Loading...", zh: "載入中..." },
  lectionaryError: { en: "Could not fetch readings", zh: "無法獲取經課" },
};

export const KNOWLEDGE_LEVEL_LABELS: {[key in KnowledgeLevel]: {en: string, zh: string}} = {
  [KnowledgeLevel.Beginner]: { en: 'Beginner', zh: '初學者' },
  [KnowledgeLevel.Intermediate]: { en: 'Intermediate', zh: '進階' },
  [KnowledgeLevel.Advanced]: { en: 'Advanced', zh: '高階' },
  [KnowledgeLevel.Scholarly]: { en: 'Scholarly', zh: '學術級' }
};

export const STUDY_TYPE_LABELS: {[key in StudyType]: {en: string, zh: string}} = {
  [StudyType.Comprehensive]: { en: 'Comprehensive Analysis', zh: '綜合分析' },
  [StudyType.Devotional]: { en: 'Devotional Study', zh: '靈修研經' },
  [StudyType.Academic]: { en: 'Academic Research', zh: '學術研究' },
  [StudyType.Sermon]: { en: 'Sermon Preparation', zh: '講章預備' },
  [StudyType.Discussion]: { en: 'Discussion Guide', zh: '討論指南' },
  [StudyType.SpiritualGuide]: { en: 'Text-Based Spiritual Guide', zh: '文本靈性導引' },
  [StudyType.NarrativeSpiritual]: { en: 'Narrative-Theological Spiritual Guide', zh: '敘事神學靈閱指引' },
  [StudyType.TorahPortion]: { en: 'Torah Portion Notes (Jewish Roots)', zh: '妥拉讀經札記 (猶太根源)' }
};

export const APPROACHES: SelectableItem[] = [
  { id: 'historical-critical', label: { en: 'Historical-Critical', zh: '歷史批判' }, description: { en: 'Source, form, and redaction criticism.', zh: '來源、形式和編輯批判。' } },
  { id: 'form', label: { en: 'Form Criticism', zh: '形式批判' }, description: { en: 'Analysis of oral units and genre.', zh: '口傳單元與體裁分析。' } },
  { id: 'source', label: { en: 'Source Criticism', zh: '來源批判' }, description: { en: 'Identifying composite literary sources.', zh: '識別複合文學來源。' } },
  { id: 'textual', label: { en: 'Textual Criticism', zh: '文本批判' }, description: { en: 'Reconstructing the original text.', zh: '重建原始文本。' } },
  { id: 'literary', label: { en: 'Literary Analysis', zh: '文學分析' }, description: { en: 'Narrative structure, genre, and literary devices.', zh: '敘事結構、體裁和文學手法。' } },
  { id: 'narrative', label: { en: 'Narrative Criticism', zh: '敘事批判' }, description: { en: 'Plot, character, and setting analysis.', zh: '情節、人物與場景分析。' } },
  { id: 'rhetorical', label: { en: 'Rhetorical Criticism', zh: '修辭批判' }, description: { en: 'Art of composition and persuasion.', zh: '寫作藝術與說服技巧。' } },
  { id: 'socio-rhetorical', label: { en: 'Socio-Rhetorical', zh: '社會修辭' }, description: { en: 'Persuasion within social texture.', zh: '社會脈絡中的說服策略。' } },
  { id: 'intertextual', label: { en: 'Intertextual', zh: '互文性' }, description: { en: 'Echoes and allusions to other texts.', zh: '對其他文本的迴響與引喻。' } },
  { id: 'feminist', label: { en: 'Feminist/Womanist', zh: '女性主義/婦女' }, description: { en: 'Gender dynamics and marginalized voices.', zh: '性別動態與邊緣化群體的聲音。' } },
  { id: 'postcolonial', label: { en: 'Postcolonial', zh: '後殖民' }, description: { en: 'Power dynamics and empire critique.', zh: '權力動態與帝國批判。' } },
  { id: 'liberation', label: { en: 'Liberation Theology', zh: '解放神學' }, description: { en: 'Perspective of the poor and oppressed.', zh: '貧窮與受壓迫者的視角。' } },
  { id: 'ideological', label: { en: 'Ideological', zh: '意識形態批判' }, description: { en: 'Uncovering political/social agendas.', zh: '揭露政治/社會議程。' } },
  { id: 'marxist', label: { en: 'Marxist/Materialist', zh: '馬克思/唯物' }, description: { en: 'Class struggle and economic base.', zh: '階級鬥爭與經濟基礎。' } },
  { id: 'queer', label: { en: 'Queer Theory', zh: '酷兒理論' }, description: { en: 'Destabilizing normative categories.', zh: '動搖規範性範疇。' } },
  { id: 'deconstructive', label: { en: 'Deconstructive', zh: '解構主義' }, description: { en: 'Meaning instability and contradiction.', zh: '意義的不穩定性與矛盾。' } },
  { id: 'psychological', label: { en: 'Psychological', zh: '心理學' }, description: { en: 'Psychological dimensions of text/author.', zh: '文本與作者的心理層面。' } },
  { id: 'psychoanalytic', label: { en: 'Psychoanalytic', zh: '精神分析' }, description: { en: 'Unconscious desires and repression.', zh: '潛意識慾望與壓抑。' } },
  { id: 'trauma', label: { en: 'Trauma Studies', zh: '創傷研究' }, description: { en: 'Impact of catastrophic events on text.', zh: '災難性事件對文本的影響。' } },
  { id: 'affect', label: { en: 'Affect Theory', zh: '情感理論' }, description: { en: 'Pre-cognitive bodily intensities.', zh: '前認知的身體強度。' } },
  { id: 'canonical', label: { en: 'Canonical Approach', zh: '正典批判' }, description: { en: 'Theological significance within canon.', zh: '整本正典中的神學意義。' } },
  { id: 'theological', label: { en: 'Theological', zh: '神學詮釋' }, description: { en: 'Divine revelation and systematics.', zh: '神聖啟示與系統神學。' } },
  { id: 'reader-response', label: { en: 'Reader-Response', zh: '讀者反應' }, description: { en: 'Meaning created by reader interaction.', zh: '讀者互動產生的意義。' } },
  { id: 'social-scientific', label: { en: 'Social-Scientific', zh: '社會科學' }, description: { en: 'Ancient social structures/anthropology.', zh: '古代社會結構與人類學。' } },
  { id: 'ecological', label: { en: 'Ecological', zh: '生態神學' }, description: { en: 'God, humanity, and earth relationship.', zh: '神、人與大地的關係。' } },
  { id: 'missional', label: { en: 'Missional', zh: '宣教' }, description: { en: 'Reading with God\'s mission in view.', zh: '以神的宣教為視角。' } },
  { id: 'reception', label: { en: 'Reception History', zh: '接受史' }, description: { en: 'History of interpretation effects.', zh: '詮釋效果的歷史。' } },
  { id: 'custom', label: { en: 'Custom Approach', zh: '自訂詮釋方法' }, description: { en: 'Define your own specific lens.', zh: '定義您自己的特定視角。' } },
];

export const TRADITIONS: SelectableItem[] = [
  { id: 'anglican', label: { en: 'Anglican', zh: '聖公宗' }, description: { en: 'Scripture, Tradition, Reason & Critical Orthodoxy.', zh: '聖經、傳統與理性的動態交響（批判性正統）。' } },
  { id: 'second-temple', label: { en: 'Second Temple', zh: '第二聖殿時期' }, description: { en: 'Intertestamental Jewish context.', zh: '兩約之間的猶太背景。' } },
  { id: 'samaritan', label: { en: 'Samaritan', zh: '撒馬利亞' }, description: { en: 'Samaritan Pentateuch and traditions.', zh: '撒馬利亞五經與傳統。' } },
  { id: 'early-jewish', label: { en: 'Early Jewish/Rabbinic', zh: '早期猶太/拉比' }, description: { en: 'Mishnah, Talmud, and Midrash.', zh: '米示拿、塔木德與米德拉什。' } },
  { id: 'diasporic', label: { en: 'Diasporic', zh: '散居猶太' }, description: { en: 'Hellenistic Judaism (e.g., Philo).', zh: '希臘化猶太教（如斐羅）。' } },
  { id: 'patristic', label: { en: 'Patristic', zh: '教父時期' }, description: { en: 'Early church fathers and councils.', zh: '早期教父與大公會議。' } },
  { id: 'eastern-orthodoxy', label: { en: 'Eastern Orthodoxy', zh: '東正教' }, description: { en: 'Byzantine theology and mysticism.', zh: '拜占庭神學與神秘主義。' } },
  { id: 'medieval-western', label: { en: 'Medieval Western', zh: '中世紀西方' }, description: { en: 'Scholasticism (Aquinas) and monasticism.', zh: '經院哲學（阿奎那）與修道主義。' } },
  { id: 'reformation', label: { en: 'Reformation', zh: '宗教改革' }, description: { en: 'Luther, Calvin, and the Radical Reformation.', zh: '路德、加爾文與激進改革。' } },
  { id: 'modern-western', label: { en: 'Western Academic', zh: '西方學術' }, description: { en: 'Critical scholarship since Enlightenment.', zh: '啟蒙運動以來的批判學術。' } },
  { id: 'evangelical', label: { en: 'Evangelical', zh: '福音派' }, description: { en: 'High view of scripture and personal piety.', zh: '重視聖經權威與個人虔誠。' } },
  { id: 'catholic-modern', label: { en: 'Modern Catholic', zh: '現代天主教' }, description: { en: 'Post-Vatican II biblical scholarship.', zh: '梵二後的聖經學術。' } },
  { id: 'majority-world', label: { en: 'Majority World', zh: '多數世界' }, description: { en: '亞洲、非洲與拉丁美洲的聲音。', zh: '亞洲、非洲與拉丁美洲的聲音。' } },
  { id: 'pentecostal', label: { en: 'Pentecostal', zh: '五旬節派' }, description: { en: 'Emphasis on Spirit, experience, and affections.', zh: '強調聖靈、經驗與情感。' } },
];
